spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    driver: mysql
    url: r2dbc:mysql://localhost:3306/player_db
    username: root
    password: admin123
    pool:
      enabled: true
      initial-size: 5
      max-size: 50
      validate: auto
      acquire-timeout: 30s
    generate-ddl: true
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
