spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:mysql://localhost:3306/player_db
    username: root
    password: admin123
    pool:
      enabled: false
      initial-size: 5
server:
  port: 8080
